services:
  server:
    build:
      context: ./server

    container_name: url-checker-server

    ports:
      - "3000:3000"

    volumes:
      - ./server:/app
      - /app/node_modules

    environment:
      NODE_ENV: development

  client:
    build:
      context: ./client

    container_name: url-checker-client

    ports:
      - "5173:5173"

    volumes:
      - ./client:/app
      - /app/node_modules

    depends_on:
      - server
