/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get jobs list */
        get: operations["JobsController_findAll"];
        put?: never;
        /** Create URL validation job */
        post: operations["JobsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job details */
        get: operations["JobsController_findOne"];
        put?: never;
        post?: never;
        /** Cancel job */
        delete: operations["JobsController_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateJobDto: {
            /**
             * @description List of URLs to validate
             * @example [
             *       "https://google.com",
             *       "https://github.com"
             *     ]
             */
            urls: string[];
        };
        CreateJobResponseDto: {
            /** @example 2d7f3c89-87c9-44f2-bfa9-8d4c2cb1a9c2 */
            jobId: string;
        };
        JobListItemDto: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            status: "pending" | "in_progress" | "completed" | "cancelled" | "failed";
            total: number;
            success: number;
            errors: number;
        };
        JobProgressDto: {
            total: number;
            processed: number;
            success: number;
            errors: number;
        };
        UrlResultDto: {
            url: string;
            /** @enum {string} */
            status: "pending" | "in_progress" | "success" | "error" | "cancelled";
            httpStatus?: number | null;
            error?: string | null;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            duration?: number | null;
        };
        JobDetailsDto: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            /** @enum {string} */
            status: "pending" | "in_progress" | "completed" | "cancelled" | "failed";
            cancelled: boolean;
            progress: components["schemas"]["JobProgressDto"];
            urls: components["schemas"]["UrlResultDto"][];
        };
        CancelJobResponseDto: {
            success: boolean;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListItemDto"][];
                };
            };
        };
    };
    JobsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponseDto"];
                };
            };
        };
    };
    JobsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailsDto"];
                };
            };
        };
    };
    JobsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelJobResponseDto"];
                };
            };
        };
    };
}
